apiVersion: v1
kind: Namespace
metadata:
  name: ocp-channel-information
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-channel-info
  namespace: ocp-channel-information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-channel-info
  template:
    metadata:
      labels:
        app: ocp-channel-info
    spec:
      containers:
        - env:
            - name: API_MODE
              value: "true"
          image: ghcr.io/backchristoffer/ocp-channel-info:latest
          name: ocp-channel-info
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ocp-channel-info-service
  namespace: ocp-channel-information
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ocp-channel-info
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocp-channel-info-route
  namespace: ocp-channel-information
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: ocp-channel-info-service
